version: '3.7'
services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: quai-antique
    restart: always
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/database

volumes:
  postgres:
    name: nest-db

api:
  build: .
  command: sh -c 'printenv && npm run start:dev'
  ports:
    - '8080:8080'
  depends-on:
    - postgres
  environment:
    DATABASE_HOST: ${POSTGRESQL_ADDON_HOST}
    DATABASE_PORT: ${POSTGRESQL_ADDON_PORT}
    DATABASE_USER: ${POSTGRESQL_ADDON_USER}
    DATABASE_PASSWORD: ${POSTGRESQL_ADDON_PASSWORD}
    DATABASE_DB: ${POSTGRESQL_ADDON_DB}