version: '3.7'

networks:
  antiqueapi:
  
services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: quai-antique
    restart: always
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/database

  adminer:
    image: adminer:4
    ports:
      - 8080:8080
    networks:
      - antiqueapi

volumes:
  postgres:
    name: nest-db